services:
  postgresql:
    container_name: "postgresql"
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgresql_data:/var/lib/postgresql/data

  adminer:
    container_name: "adminer"
    image: adminer
    restart: always
    ports:
      - 8085:8080

