services:

  registry:
    image: registry:2
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./volumes/registry_data:/var/lib/registry

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "50001:8080"
      - "50000:50000"
    volumes:
      - ./volumes/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root