services:

  registry:
    container_name: "docker-registery"
    image: registry:latest
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./volumes/registry_data:/var/lib/registry

  jenkins:
    container_name: "jenkins"
    image: "jenkins"
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./volumes/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock