pipeline {
  agent any

  environment {
    REGISTRY = 'docker-registery.local'
    BASE_IMAGE = 'nx-builder-base'
    NEXT_IMAGE = "${REGISTRY}/next-app:latest"
    EXPRESS_IMAGE = "${REGISTRY}/express-app:latest"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build Nx Base Image') {
      steps {
        script {
          sh '''
            docker build -f ./docker/app/Dockerfile.builder-base -t $BASE_IMAGE .
          '''
        }
      }
    }

  }

  post {
    failure {
      echo 'Build failed!'
    }
    success {
      echo 'All images built and pushed successfully.'
    }
  }
}