pipeline {
  agent any

  environment {
    REGISTRY = 'docker-registery.local'
    BASE_IMAGE = 'nx-builder-base'
    NEXT_IMAGE = "${REGISTRY}/next-app:latest"
    EXPRESS_IMAGE = "${REGISTRY}/express-app:latest"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install Dependencies'){
      steps{
        script {
          sh 'npm i'
        }
      }
    }

    stage('DB setup') {
      steps {
        script {
            sh 'npm run prisma:migrate'
        }
        script {
            sh 'npm run prisma:reset:force'
        }
      }
    }

    stage('Build') {
      steps {
        script {
            sh 'npx nx run-many --target=build --all'
        }
      }
    }

    stage('Lint') {
      steps {
        script {
            sh 'npx nx run-many --target=lint --all'
        }
      }
    }

    stage('Test') {
      steps {
        script {
            sh 'npx nx run-many --target=test --all'
        }
      }
    }
  }

  post {
    failure {
      echo 'Build failed!'
    }
    success {
      echo 'All images built and pushed successfully.'
    }
  }
}